/*****************************************************************************

    Wavelet decomposition
  
  NB: filter data is stored in dwt.h (generated by DWTpy2c.py)

****************************************************************/

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dwt.h"

// Applies LP FIR filter and downsamples by 2
int downsamplingConvolution_l( double* input, int inlen, double* output ){
  int outlen = (inlen + F_l - 1)>>1;
  
  int i = 1;
  int o = 0;
  while((i<F_l) & (i<inlen)){
    double sum = 0;
    int j=0;
    while(j<i){
      sum = sum + filter_l[j]*input[i-j];
      j = j+1;
    }
    while(j < F_l){ 
      sum = sum + filter_l[j]*input[0];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  
  while(i < inlen){
    double sum = 0;
    int j=0;
    while(j < F_l){
      sum = sum + filter_l[j]*input[i-j];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  
  while(i < (inlen+F_l-1)){
    double sum = 0;
    int j=0;
    while((i-j) >= inlen){
      sum = sum + filter_l[j]*input[inlen-1];
      j = j+1;
    }
    while(j < F_l){
      sum = sum + filter_l[j]*input[i-j];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  return outlen;
}

// Applies HP FIR filter and downsamples by 2
int downsamplingConvolution_h( double* input, int inlen, double* output ){
  int outlen = (inlen + F_h - 1)>>1;
  
  int i = 1;
  int o = 0;
  while((i<F_h) & (i<inlen)){
    double sum = 0;
    int j=0;
    while(j<i){
      sum = sum + filter_h[j]*input[i-j];
      j = j+1;
    }
    while(j < F_h){ 
      sum = sum + filter_h[j]*input[0];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  
  while(i < inlen){
    double sum = 0;
    int j=0;
    while(j < F_h){
      sum = sum + filter_h[j]*input[i-j];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  
  while(i < (inlen+F_h-1)){
    double sum = 0;
    int j=0;
    while((i-j) >= inlen){
      sum = sum + filter_h[j]*input[inlen-1];
      j = j+1;
    }
    while(j < F_h){
      sum = sum + filter_h[j]*input[i-j];
      j = j+1;
    }
    output[o] = sum;
    i = i+2;
    o = o+1;
  }
  return outlen;
}

int dwtbufferlen(int N, int Fl, int Fh, int level){
  int len = 0;
  int levellen = N;
  for(int i = 0; i<level; i++){
    len = len + ((levellen+Fh-1)>>1);
    levellen = ((levellen+Fl-1)>>1);
  }
  len = len + levellen;
  return len;
} 

double* wavedec(double* input, int inlen, int level, int* outlen){
  int len_tot = dwtbufferlen(inlen,F_l,F_h,level);
  int levellen_l = inlen;
  int levellen_h = 0;
  double* output = malloc(len_tot*sizeof(double));
  double* out_ptr = output;
  double* in_buffer = malloc(inlen*sizeof(double));
  double* temp_buffer = malloc(inlen*sizeof(double));
  memcpy(in_buffer, input, inlen*sizeof(double));
  for(int i = 0; i<level; i++){
    levellen_h = downsamplingConvolution_h(in_buffer, levellen_l, out_ptr);
    levellen_l = downsamplingConvolution_l(in_buffer, levellen_l, temp_buffer);
    memcpy(in_buffer, temp_buffer, levellen_l*sizeof(double));
    out_ptr = out_ptr+levellen_h;
  }
  memcpy(out_ptr, temp_buffer, levellen_l*sizeof(double));
  //for(int j = 0; j<len_tot; j++){
  //  printf("%f, ",output[j]);
  //}
  //printf("\n");
  
  free(in_buffer);
  free(temp_buffer);
  
  *outlen = len_tot;
  
  return output;
}
