/*****************************************************************************

    SVM classification 
  
  NB: inference only, no training
  SVM model data is stored in smv.h (generated by SVMpy2c.py)

****************************************************************/

#include <math.h>
#include <stdio.h>
#include "svm.h"

// Classifies data point x using the model in svm.h
int svm_predict( double* x, double* dec_values )
	{
    int p = 0;
    int vote[3] = {0,0,0};
    
		for(int i=0;i<3;i++)
    {
			for(int j=i+1;j<3;j++)
			{
				double sum = 0;
				int si = start_sv[i];
				int sj = start_sv[j];
				int ci = n_sv[i];
				int cj =n_sv[j];

				int k;
        int f;
				double *coef1 = sv_coef[j-1];
				double *coef2 = sv_coef[i];
        
				for(k=si;k<(si+ci);k++)
        {
          double dist = 0;
          for(f=0;f<n_feat;f++)
          {
            double diff = x[f] - sv[k][f];
            dist += diff*diff;
          }
					sum += coef1[k] * exp(-gam*dist);
        }
				for(k=sj;k<(sj+cj);k++)
				{
          double dist = 0;
          for(f=0;f<n_feat;f++)
          {
            double diff = x[f] - sv[k][f];
            dist += diff*diff;
          }
					sum += coef2[k] * exp(-gam*dist);
        }
				sum += rho[p];
				dec_values[p] = sum;
        
        if(dec_values[p] > 0)
					++vote[i];
				else
					++vote[j];
        
        p++;
			}
    }
    
    int vote_max_idx = 0;
		for(int i=1;i<3;i++)
			if(vote[i] > vote[vote_max_idx])
				vote_max_idx = i;
      
		return vote_max_idx+1;
	}
