/*****************************************************************************

    SVM classification 
  
  NB: inference only, no training
  SVM model data is stored in smv.h (generated by SVMpy2c.py)

****************************************************************/

#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include "svm_int.h"

uint64_t exp_custom(uint32_t x, int shift);

// Classifies data point x using the model in svm.h
int svm_predict( int* x, double* dec_values )
	{
    int p = 0;
    int vote[3] = {0,0,0};
    
		for(int i=0;i<3;i++)
    {
			for(int j=i+1;j<3;j++)
			{
				int64_t sum = 0;
				int si = start_sv[i];
				int sj = start_sv[j];
				int ci = n_sv[i];
				int cj =n_sv[j];

				int k;
        int f;
				int32_t *coef1 = sv_coef[j-1];
				int32_t *coef2 = sv_coef[i];
        
				for(k=si;k<(si+ci);k++) 
        {
          int64_t dist = 0;
          for(f=0;f<n_feat;f++)
          {
            int64_t diff = x[f] - sv[k][f]; 
            dist += diff*diff;
          }
          sum += coef1[k] * exp_custom(dist/gam_inv,shift);
        }
				for(k=sj;k<(sj+cj);k++)
				{
          int64_t dist = 0;
          for(f=0;f<n_feat;f++) 
          {
            int64_t diff = x[f] - sv[k][f];
            dist += diff*diff;
          }
					sum += coef2[k] * exp_custom(dist/gam_inv,shift);
        }
				sum += rho[p];
				dec_values[p] = sum;
        
        if(dec_values[p] > 0)
					++vote[i];
				else
					++vote[j];
        
        p++;
			}
    }
    
    int vote_max_idx = 0;
		for(int i=1;i<3;i++)
			if(vote[i] > vote[vote_max_idx])
				vote_max_idx = i;
      
		return vote_max_idx+1;
	}

uint64_t exp_custom(uint32_t x, int shift){
  
  int index = (-shift<exp_ai_min)?exp_ai_min:-shift;
  uint64_t val = 1U<<exp_shift;
  uint64_t mask = 1U<<(index+shift);
  if((x>>(shift+exp_ai_max))>0){
    val = 0;
  }else{
    for(;index<=exp_ai_max;index++){
      if(mask & x){
        val = (val*exp_ai[index-exp_ai_min])>>exp_shift;
      }
      mask = mask<<1;
    }
  }
  return val;
}